services:
  db:
    image: postgres:16
    container_name: lowlimit_db
    restart: always
    environment:
      POSTGRES_DB: lowlimit
      POSTGRES_USER: lluser
      POSTGRES_PASSWORD: llpassword
    ports:
      - "5435:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
