# Generated by Django 6.0.3 on 2026-03-31 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0002_add_wager_spread_to_wager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sportingevent',
            name='gender',
            field=models.CharField(choices=[('M', "Men's"), ('W', "Women's"), ('B', 'MLB')], default='M', max_length=1),
        ),
    ]
